# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@postman/csv-parse-4.0.2" = {
      name = "_at_postman_slash_csv-parse";
      packageName = "@postman/csv-parse";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@postman/csv-parse/-/csv-parse-4.0.2.tgz";
        sha512 = "fopt7VY/srspxfPz2tJdR41z9fGTjbuwcKRxWTqwXjcutJBBgHp+ot8Vr5oa5XO5sGHEbPNyX9mxtsJso8oVYw==";
      };
    };
    "@postman/tunnel-agent-0.6.3" = {
      name = "_at_postman_slash_tunnel-agent";
      packageName = "@postman/tunnel-agent";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@postman/tunnel-agent/-/tunnel-agent-0.6.3.tgz";
        sha512 = "k57fzmAZ2PJGxfOA4SGR05ejorHbVAa/84Hxh/2nAztjNXc4ZjOm9NUIk6/Z6LCrBvJZqjRZbN8e/nROVUPVdg==";
      };
    };
    "ajv-6.10.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "6.10.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-6.10.2.tgz";
        sha512 = "TXtUUEYHuaTEbLZWIKUr5pmBuhDLy+8KYtPYdcV8qC+pOZL+NKqYwvWSRrVXHn+ZmRRAu8vJTAznH7Oag6RVRw==";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-regex-3.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-3.0.0.tgz";
        sha1 = "ed0317c322064f79466c02966bddb605ab37d998";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "array-uniq-1.0.3" = {
      name = "array-uniq";
      packageName = "array-uniq";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-uniq/-/array-uniq-1.0.3.tgz";
        sha1 = "af6ac877a25cc7f74e058894753858dfdb24fdb6";
      };
    };
    "asn1-0.2.4" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.4.tgz";
        sha512 = "jxwzQpLQjSmWXgwaCZE9Nz+glAG01yF1QnWgbhGwHI5A6FRIEY6IVqtHhIepHqI7/kyEyQEagBC5mBEFlIYvdg==";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "async-2.6.2" = {
      name = "async";
      packageName = "async";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.6.2.tgz";
        sha512 = "H1qVYh1MYhEEFLsP97cVKqCGo7KfCyTt6uEWqsTBr9SO84oK9Uwbyd/yCW+6rKJLHksBNUVWZDAjfS+Ccx0Bbg==";
      };
    };
    "async-3.1.0" = {
      name = "async";
      packageName = "async";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-3.1.0.tgz";
        sha512 = "4vx/aaY6j/j3Lw3fbCHNWP0pPaTCew3F6F3hYyl/tHs/ndmV1q7NW9T5yuJ2XAGwdQrP+6Wu20x06U4APo/iQQ==";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "aws-sign2-0.7.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz";
        sha1 = "b46e890934a9591f2d2f6f86d7e6a9f1b3fe76a8";
      };
    };
    "aws4-1.9.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.9.0.tgz";
        sha512 = "Uvq6hVe90D0B2WEnUqtdgY1bATGz3mw33nH9Y+dmA+w5DHvUmBgkr5rM/KCHpCsiFNRUfokW/szpPPgMK2hm4A==";
      };
    };
    "bcrypt-pbkdf-1.0.2" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.2.tgz";
        sha1 = "a4301d389b6a43f9b67ff3ca11a3f6637e360e9e";
      };
    };
    "bluebird-2.11.0" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-2.11.0.tgz";
        sha1 = "534b9033c022c9579c56ba3b3e5a5caafbb650e1";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "chardet-0.8.0" = {
      name = "chardet";
      packageName = "chardet";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chardet/-/chardet-0.8.0.tgz";
        sha512 = "fRAe54sDSPvCz9I3puKUoUpLBEIUjlwBoNyNcD2eAiP5Ybw2iXnrT7w15hfkNywosXFNllWwvOKsxl7UUCKQaQ==";
      };
    };
    "charset-1.0.1" = {
      name = "charset";
      packageName = "charset";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/charset/-/charset-1.0.1.tgz";
        sha512 = "6dVyOOYjpfFcL1Y4qChrAoQLRHvj2ziyhcm0QJlhOcAhykL/k1kTUPbeo+87MNRTRdk2OIIsIXbuF3x2wi5EXg==";
      };
    };
    "cli-progress-3.4.0" = {
      name = "cli-progress";
      packageName = "cli-progress";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-progress/-/cli-progress-3.4.0.tgz";
        sha512 = "35zcc1FsbPfN2dVonxUQwEnqMnI5kDFx2G4qGFGWgIDYqZ6+3t4/GjX/Vk0tq6bNgI9dEFcWLJ6AaLN17NLBDA==";
      };
    };
    "cli-table3-0.5.1" = {
      name = "cli-table3";
      packageName = "cli-table3";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-table3/-/cli-table3-0.5.1.tgz";
        sha512 = "7Qg2Jrep1S/+Q3EceiZtQcDPWxhAvBw+ERf1162v4sikJrvojMHFqXt8QIVha8UlH9rgU0BeWPytZ9/TzYqlUw==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "colors-1.4.0" = {
      name = "colors";
      packageName = "colors";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.4.0.tgz";
        sha512 = "a+UqTh4kgZg/SlGvfbzDHpgRu7AAQOmmqRHJnxhRZICKFUT91brVhNNt58CMWU9PsBbv3PDCZUHbVxuDiH2mtA==";
      };
    };
    "combined-stream-1.0.8" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.8.tgz";
        sha512 = "FQN4MRfuJeHf7cBbBMJFXhKSDq+2kAArBlmRBvcvFE5BB1HZKXtSFASDhdlz9zOYwxh8lDdnvmMOe/+5cdoEdg==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "commander-3.0.1" = {
      name = "commander";
      packageName = "commander";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-3.0.1.tgz";
        sha512 = "UNgvDd+csKdc9GD4zjtkHKQbT8Aspt2jCBqNSPp53vAS0L1tS9sXB2TCEOPHJ7kt9bN/niWkYj8T3RQSoMXdSQ==";
      };
    };
    "commander-4.0.1" = {
      name = "commander";
      packageName = "commander";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-4.0.1.tgz";
        sha512 = "IPF4ouhCP+qdlcmCedhxX4xiGBPyigb8v5NeUp+0LyhwLgxMqyp3S0vl7TAPfS/hiP7FC3caI/PB9lTmP8r1NA==";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "crypto-js-3.1.9-1" = {
      name = "crypto-js";
      packageName = "crypto-js";
      version = "3.1.9-1";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-js/-/crypto-js-3.1.9-1.tgz";
        sha1 = "fda19e761fc077e01ffbfdc6e9fdfc59e8806cd8";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "dbug-0.4.2" = {
      name = "dbug";
      packageName = "dbug";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dbug/-/dbug-0.4.2.tgz";
        sha1 = "32b4b3105e8861043a6f9ac755d80e542d365b31";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "dom-serializer-0.2.2" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.2.2.tgz";
        sha512 = "2/xPb3ORsQ42nHYiSunXkDjPLBaEj/xTwUO4B7XCZQTRk7EBtTOPaygh10YAAh2OI1Qrp6NWfpAhzswj0ydt9g==";
      };
    };
    "domelementtype-1.3.1" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.1.tgz";
        sha512 = "BSKB+TSpMpFI/HOxCNr1O8aMOTZ8hT3pM3GQ0w/mWRmkhEDSFJkkyzz4XQsBV44BChwGkrDfMyjVD0eA2aFV3w==";
      };
    };
    "domelementtype-2.0.1" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.0.1.tgz";
        sha512 = "5HOHUDsYZWV8FGWN0Njbr/Rn7f/eWSQi1v7+HsUVwXgn8nWWlL64zKDkS0n8ZmQ3mlWOMuXOnR+7Nx/5tMO5AQ==";
      };
    };
    "domhandler-2.4.2" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-2.4.2.tgz";
        sha512 = "JiK04h0Ht5u/80fdLMCEmV4zkNh2BcoMFBmZ/91WtYZ8qVXSKjiw7fXMgFPnHcSZgOo3XdinHvmnDUeMf5R4wA==";
      };
    };
    "domutils-1.7.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.7.0.tgz";
        sha512 = "Lgd2XcJ/NjEw+7tFvfKxOzCYKZsdct5lczQ2ZaQY8Djz7pfAD3Gbp8ySJWtreII/vDlMVmxwa6pHmdxIYgttDg==";
      };
    };
    "ecc-jsbn-0.1.2" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.2.tgz";
        sha1 = "3a83a904e54353287874c564b7549386849a98c9";
      };
    };
    "entities-1.1.2" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.2.tgz";
        sha512 = "f2LZMYl1Fzu7YSBKg+RoROelpOaNrcGmE9AZubeDfrCEia483oW4MI4VyFd5VNHIgQ/7qm1I0wUHK1eJnn2y2w==";
      };
    };
    "entities-2.0.0" = {
      name = "entities";
      packageName = "entities";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.0.0.tgz";
        sha512 = "D9f7V0JSRwIxlRI2mjMqufDrRDnx8p+eEOz7aUM9SuvF8gsBzra0/6tbjl1m8eQHrZlYj6PxqE00hZ1SAIKPLw==";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "eventemitter3-4.0.0" = {
      name = "eventemitter3";
      packageName = "eventemitter3";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter3/-/eventemitter3-4.0.0.tgz";
        sha512 = "qerSRB0p+UDEssxTtm6EDKcE7W4OaoisfIMl4CngyEhjpYglocpNg6UEqCvemdGhosAsg4sO2dXJOdyBifPGCg==";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "faker-4.1.0" = {
      name = "faker";
      packageName = "faker";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/faker/-/faker-4.1.0.tgz";
        sha1 = "1e45bbbecc6774b3c195fad2835109c6d748cc3f";
      };
    };
    "fast-deep-equal-2.0.1" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-2.0.1.tgz";
        sha1 = "7b05218ddf9667bf7f370bf7fdb2cb15fdd0aa49";
      };
    };
    "fast-json-stable-stringify-2.1.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz";
        sha512 = "lhd/wF+Lk98HZoTCtlVraHtfh5XYijIjalXck7saUtuanSDyLMxnHhSXEDJqHxD7msR8D0uCmqlkwjCV8xvwHw==";
      };
    };
    "file-type-3.9.0" = {
      name = "file-type";
      packageName = "file-type";
      version = "3.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-type/-/file-type-3.9.0.tgz";
        sha1 = "257a078384d1db8087bc449d107d52a52672b9e9";
      };
    };
    "filesize-6.0.1" = {
      name = "filesize";
      packageName = "filesize";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/filesize/-/filesize-6.0.1.tgz";
        sha512 = "u4AYWPgbI5GBhs6id1KdImZWn5yfyFrrQ8OWZdN7ZMfA8Bf4HcO0BGo9bmUIEV8yrp8I1xVfJ/dn90GtFNNJcg==";
      };
    };
    "flatted-2.0.1" = {
      name = "flatted";
      packageName = "flatted";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/flatted/-/flatted-2.0.1.tgz";
        sha512 = "a1hQMktqW9Nmqr5aktAux3JMNqaucxGcjtjWnZLHX7yyPCmlSV3M54nGYbqT8K+0GhF3NBgmJCc3ma+WOgX8Jg==";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.3.3" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.3.tgz";
        sha512 = "1lLKB2Mu3aGP1Q/2eCOx0fNbRMe7XdwktwOruhfqqd0rIJWwN4Dh+E3hrPSlDCXnSR7UtZ1N38rVXm+6+MEhJQ==";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "handlebars-4.5.3" = {
      name = "handlebars";
      packageName = "handlebars";
      version = "4.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/handlebars/-/handlebars-4.5.3.tgz";
        sha512 = "3yPecJoJHK/4c6aZhSvxOyG4vJKDshV36VHp0iVCDVh7o9w2vwi3NSnL2MMPj3YdduqaBcu7cGbggJQM0br9xA==";
      };
    };
    "har-schema-2.0.0" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz";
        sha1 = "a94c2224ebcac04782a0d9035521f24735b7ec92";
      };
    };
    "har-validator-5.1.3" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "5.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-5.1.3.tgz";
        sha512 = "sNvOCzEQNr/qrvJgc3UG/kD4QtlHycrzwS+6mfTrrSq97BvaYcPZZI1ZSqGSPR73Cxn4LKTD4PttRwfU7jWq5g==";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "htmlparser2-3.10.1" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "3.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.10.1.tgz";
        sha512 = "IgieNijUMbkDovyoKObU1DUhm1iwNYE/fuifEoEHfd1oZKZDaONBSkal7Y01shxsM49R4XaMdGez3WnF9UfiCQ==";
      };
    };
    "http-reasons-0.1.0" = {
      name = "http-reasons";
      packageName = "http-reasons";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-reasons/-/http-reasons-0.1.0.tgz";
        sha1 = "a953ca670078669dde142ce899401b9d6e85d3b4";
      };
    };
    "http-signature-1.2.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz";
        sha1 = "9aecd925114772f3d95b65a60abb8f7c18fbace1";
      };
    };
    "httpntlm-1.7.6" = {
      name = "httpntlm";
      packageName = "httpntlm";
      version = "1.7.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/httpntlm/-/httpntlm-1.7.6.tgz";
        sha1 = "6991e8352836007d67101b83db8ed0f915f906d0";
      };
    };
    "httpreq-0.4.24" = {
      name = "httpreq";
      packageName = "httpreq";
      version = "0.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/httpreq/-/httpreq-0.4.24.tgz";
        sha1 = "4335ffd82cd969668a39465c929ac61d6393627f";
      };
    };
    "iconv-lite-0.5.0" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.5.0.tgz";
        sha512 = "NnEhI9hIEKHOzJ4f697DMz9IQEXr/MMJ5w64vN2/4Ai+wRnvV7SBrL0KLoRlwaKVghOc7LQ5YkPLuX146b6Ydw==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "intel-1.2.0" = {
      name = "intel";
      packageName = "intel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/intel/-/intel-1.2.0.tgz";
        sha1 = "11d1147eb6b3f4582bdf5337b37d541584e9e41e";
      };
    };
    "ip-regex-2.1.0" = {
      name = "ip-regex";
      packageName = "ip-regex";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip-regex/-/ip-regex-2.1.0.tgz";
        sha1 = "fa78bf5d2e6913c911ce9f819ee5146bb6d844e9";
      };
    };
    "is-fullwidth-code-point-2.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-2.0.0.tgz";
        sha1 = "a3b30a5c4f199183167aaab93beefae3ddfb654f";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "json-schema-traverse-0.4.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.4.1.tgz";
        sha512 = "xbbCH5dCYU5T8LcEhhuh7HJ88HXuW3qsI3Y0zOZFKfZEHcpWiHU/Jxzk629Brsab/mMiHQti9wMP+845RPe3Vg==";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "liquid-json-0.3.1" = {
      name = "liquid-json";
      packageName = "liquid-json";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/liquid-json/-/liquid-json-0.3.1.tgz";
        sha1 = "9155a18136d8a6b2615e5f16f9a2448ab6b50eea";
      };
    };
    "lodash-4.17.15" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.15.tgz";
        sha512 = "8xOcRHvCjnocdS5cpwXQXVzmmh5e5+saE2QGoeQmbKmRS6J3VQppPOIt0MnmE+4xlZoumy0GPG0D0MVIQbNA1A==";
      };
    };
    "lodash.clonedeep-4.5.0" = {
      name = "lodash.clonedeep";
      packageName = "lodash.clonedeep";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.clonedeep/-/lodash.clonedeep-4.5.0.tgz";
        sha1 = "e23f3f9c4f8fbdde872529c1071857a086e5ccef";
      };
    };
    "lodash.escaperegexp-4.1.2" = {
      name = "lodash.escaperegexp";
      packageName = "lodash.escaperegexp";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.escaperegexp/-/lodash.escaperegexp-4.1.2.tgz";
        sha1 = "64762c48618082518ac3df4ccf5d5886dae20347";
      };
    };
    "lodash.isplainobject-4.0.6" = {
      name = "lodash.isplainobject";
      packageName = "lodash.isplainobject";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-4.0.6.tgz";
        sha1 = "7c526a52d89b45c45cc690b88163be0497f550cb";
      };
    };
    "lodash.isstring-4.0.1" = {
      name = "lodash.isstring";
      packageName = "lodash.isstring";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isstring/-/lodash.isstring-4.0.1.tgz";
        sha1 = "d527dfb5456eca7cc9bb95d5daeaf88ba54a5451";
      };
    };
    "lodash.mergewith-4.6.2" = {
      name = "lodash.mergewith";
      packageName = "lodash.mergewith";
      version = "4.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.mergewith/-/lodash.mergewith-4.6.2.tgz";
        sha512 = "GK3g5RPZWTRSeLSpgP8Xhra+pnjBC56q9FZYe1d5RN3TJ35dbkGy3YqBSMbyCrlbi+CM9Z3Jk5yTL7RCsqboyQ==";
      };
    };
    "marked-0.7.0" = {
      name = "marked";
      packageName = "marked";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/marked/-/marked-0.7.0.tgz";
        sha512 = "c+yYdCZJQrsRjTPhUx7VKkApw9bwDkNbHUKo1ovgcfDjb2kc8rLuRbIFyXL5WOEUwzSSKo3IXpph2K6DqB/KZg==";
      };
    };
    "mime-db-1.42.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.42.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.42.0.tgz";
        sha512 = "UbfJCR4UAVRNgMpfImz05smAXK7+c+ZntjaA26ANtkXLlOe947Aag5zdIcKQULAiF9Cq4WxBi9jUs5zkA84bYQ==";
      };
    };
    "mime-format-2.0.0" = {
      name = "mime-format";
      packageName = "mime-format";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-format/-/mime-format-2.0.0.tgz";
        sha1 = "e29f8891e284d78270246f0050d6834bdbbe1332";
      };
    };
    "mime-types-2.1.25" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.25";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.25.tgz";
        sha512 = "5KhStqB5xpTAeGqKBAMgwaYMnQik7teQN4IAzC7npDv6kzeU6prfkR67bc87J1kWMPGkoaZSq1npmexMgkmEVg==";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "neo-async-2.6.1" = {
      name = "neo-async";
      packageName = "neo-async";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/neo-async/-/neo-async-2.6.1.tgz";
        sha512 = "iyam8fBuCUpWeKPGpaNMetEocMt364qkCsfL9JuhjXX6dRnguRVOfk2GZaDpPjcOKiiXCPINZC1GczQ7iTq3Zw==";
      };
    };
    "node-oauth1-1.2.2" = {
      name = "node-oauth1";
      packageName = "node-oauth1";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-oauth1/-/node-oauth1-1.2.2.tgz";
        sha512 = "f2XC7Y68wJq6+s+LJn/yUq5Gqg9Y9zwIz2zY6vUyS8xzawnSWhXKOMJepLwvptjPl8IjVxtWh7iI9dbdKGSw4g==";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "oauth-sign-0.9.0" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.9.0.tgz";
        sha512 = "fexhUFFPTGV8ybAtSIGbV6gOkSv8UtRbDBnAyLQw4QPKkgNlsH2ByPGtMUqdWkos6YCRmAqViwgZrJc/mRDzZQ==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "object-hash-1.3.1" = {
      name = "object-hash";
      packageName = "object-hash";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-hash/-/object-hash-1.3.1.tgz";
        sha512 = "OSuu/pU4ENM9kmREg0BdNrUDIl1heYa4mBZacJc+vVWz4GtAwu7jO8s4AIt2aGRUTqxykpWzI3Oqnsm13tTMDA==";
      };
    };
    "optimist-0.6.1" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz";
        sha1 = "da3ea74686fa21a19a111c326e90eb15a0196686";
      };
    };
    "parse-ms-2.1.0" = {
      name = "parse-ms";
      packageName = "parse-ms";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-ms/-/parse-ms-2.1.0.tgz";
        sha512 = "kHt7kzLoS9VBZfUsiKjv43mr91ea+U05EyKkEtqp7vNbHxmaVuEqN7XxeEVnGrMtYOAxGrDElSi96K7EgO1zCA==";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "postcss-7.0.26" = {
      name = "postcss";
      packageName = "postcss";
      version = "7.0.26";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-7.0.26.tgz";
        sha512 = "IY4oRjpXWYshuTDFxMVkJDtWIk2LhsTlu8bZnbEJA4+bYT16Lvpo8Qv6EvDumhYRgzjZl489pmsY3qVgJQ08nA==";
      };
    };
    "postman-collection-3.5.5" = {
      name = "postman-collection";
      packageName = "postman-collection";
      version = "3.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/postman-collection/-/postman-collection-3.5.5.tgz";
        sha512 = "W0w0wqLlMSvFSY0LYsoNKpaFcjeg+MeNOR1XK4VyX8XFDt3uAhwCe88dS23Ee/ZG7K8T83fJU8lqVk7fjOuAUA==";
      };
    };
    "postman-collection-transformer-3.2.0" = {
      name = "postman-collection-transformer";
      packageName = "postman-collection-transformer";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postman-collection-transformer/-/postman-collection-transformer-3.2.0.tgz";
        sha512 = "Z29YqacRD+G0sj5hWsmPP8FvgzT2sx2xc/fyQ/YhpP1rHosH9Q04mXKe534VcsIv3LjT25vUgMFVFLfKYHLdpg==";
      };
    };
    "postman-request-2.88.1-postman.16" = {
      name = "postman-request";
      packageName = "postman-request";
      version = "2.88.1-postman.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/postman-request/-/postman-request-2.88.1-postman.16.tgz";
        sha512 = "qXIK9aQ8JzAZA/VBWtyajEdAQNbPuVVRXuzhzXUuPcdaFYeZgj2PUZXkml6KhGB8zg8FP6/l53gHLA56IRV7Cw==";
      };
    };
    "postman-runtime-7.21.0" = {
      name = "postman-runtime";
      packageName = "postman-runtime";
      version = "7.21.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postman-runtime/-/postman-runtime-7.21.0.tgz";
        sha512 = "3wxxbcYT+AWDCrnGC2JQ4LHYbVZ7Mc9xkQoWyp1xHJifzxVCCalaxkUMIGVcrb+Za5uUpXqhsB5Kl7Xg276ruA==";
      };
    };
    "postman-sandbox-3.5.2" = {
      name = "postman-sandbox";
      packageName = "postman-sandbox";
      version = "3.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postman-sandbox/-/postman-sandbox-3.5.2.tgz";
        sha512 = "2+dMUNVdSOHJhyJml4RVdzcsj1FUC4A4mHg3jODp146e3tUjj5c523GdxU28QvCuY4g2bw6awkd9ZAkDtmccmA==";
      };
    };
    "postman-url-encoder-1.0.1" = {
      name = "postman-url-encoder";
      packageName = "postman-url-encoder";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postman-url-encoder/-/postman-url-encoder-1.0.1.tgz";
        sha1 = "a094a42e9415ff0bbfdce0eaa8e6011d449ee83c";
      };
    };
    "postman-url-encoder-1.0.3" = {
      name = "postman-url-encoder";
      packageName = "postman-url-encoder";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postman-url-encoder/-/postman-url-encoder-1.0.3.tgz";
        sha512 = "bkLjnntRHuPBQVOyGXrlrV1AWGNoZjkAI9C1pbATGzw5nLy4pOSDu5KVUsK20u6hhriFFXKUIblp0WqS3iMygw==";
      };
    };
    "pretty-ms-5.1.0" = {
      name = "pretty-ms";
      packageName = "pretty-ms";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pretty-ms/-/pretty-ms-5.1.0.tgz";
        sha512 = "4gaK1skD2gwscCfkswYQRmddUb2GJZtzDGRjHWadVHtK/DIKFufa12MvES6/xu1tVbUYeia5bmLcwJtZJQUqnw==";
      };
    };
    "psl-1.7.0" = {
      name = "psl";
      packageName = "psl";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/psl/-/psl-1.7.0.tgz";
        sha512 = "5NsSEDv8zY70ScRnOTn7bK7eanl2MvFrOrS/R6x+dBt5g1ghnj9Zv90kO8GwT8gxcu2ANyFprnFYB85IogIJOQ==";
      };
    };
    "punycode-2.1.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.1.1.tgz";
        sha512 = "XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==";
      };
    };
    "qs-6.5.2" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.2.tgz";
        sha512 = "N5ZAX4/LxJmF+7wN74pUD6qAh9/wnvdQcjq9TZjevvXzSUo7bfmw91saqMjzGS2xq91/odN2dW/WOl7qQHNDGA==";
      };
    };
    "readable-stream-3.4.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.4.0.tgz";
        sha512 = "jItXPLmrSR8jmTRmRWJXCnGJsfy85mB3Wd/uINMXA65yrnFo0cPClFIUWzo2najVNSl+mx7/4W8ttlLWJe99pQ==";
      };
    };
    "resolve-from-5.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-5.0.0.tgz";
        sha512 = "qYg9KP24dD5qka9J47d0aVky0N+b4fTU89LN9iDnjB5waksiC49rvMB0PrUJQGoTmH50XPiqOvAjDfaijGxYZw==";
      };
    };
    "safe-buffer-5.2.0" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.0.tgz";
        sha512 = "fZEwUGbVl7kouZs1jCdMLdt95hdIv0ZeHg6L7qPeciMZhZ+/gdesW4wgTARkrFWEpspjEATAzUGPG8N2jJiwbg==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sanitize-html-1.20.1" = {
      name = "sanitize-html";
      packageName = "sanitize-html";
      version = "1.20.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sanitize-html/-/sanitize-html-1.20.1.tgz";
        sha512 = "txnH8TQjaQvg2Q0HY06G6CDJLVYCpbnxrdO0WN8gjCKaU5J0KbyGYhZxx5QJg3WLZ1lB7XU9kDkfrCXUozqptA==";
      };
    };
    "semver-6.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz";
        sha512 = "b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==";
      };
    };
    "serialised-error-1.1.3" = {
      name = "serialised-error";
      packageName = "serialised-error";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/serialised-error/-/serialised-error-1.1.3.tgz";
        sha512 = "vybp3GItaR1ZtO2nxZZo8eOo7fnVaNtP3XE2vJKgzkKR2bagCkdJ1EpYYhEMd3qu/80DwQk9KjsNSxE3fXWq0g==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "srcset-1.0.0" = {
      name = "srcset";
      packageName = "srcset";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/srcset/-/srcset-1.0.0.tgz";
        sha1 = "a5669de12b42f3b1d5e83ed03c71046fc48f41ef";
      };
    };
    "sshpk-1.16.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.16.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.16.1.tgz";
        sha512 = "HXXqVUq7+pcKeLqqZj6mHFUMvXtOJt1uoUx09pFW6011inTMxqI8BA8PM95myrIyyKwdnzjdFjLiE6KBPVtJIg==";
      };
    };
    "stack-trace-0.0.10" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.10.tgz";
        sha1 = "547c70b347e8d32b4e108ea1a2a159e5fdde19c0";
      };
    };
    "stack-trace-0.0.9" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.9.tgz";
        sha1 = "a8f6eaeca90674c333e7c43953f275b451510695";
      };
    };
    "stream-length-1.0.2" = {
      name = "stream-length";
      packageName = "stream-length";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-length/-/stream-length-1.0.2.tgz";
        sha1 = "8277f3cbee49a4daabcfdb4e2f4a9b5e9f2c9f00";
      };
    };
    "strftime-0.10.0" = {
      name = "strftime";
      packageName = "strftime";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strftime/-/strftime-0.10.0.tgz";
        sha1 = "b3f0fa419295202a5a289f6d6be9f4909a617193";
      };
    };
    "string-width-2.1.1" = {
      name = "string-width";
      packageName = "string-width";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-2.1.1.tgz";
        sha512 = "nOqH59deCq9SRHlxq1Aw85Jnt4w6KvLKqWVik6oA9ZklXLNIOlqg4F2yrT1MVaTjAqvVwdfeZ7w7aCvJD7ugkw==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "strip-ansi-4.0.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-4.0.0.tgz";
        sha1 = "a8479022eb1ac368a871389b635262c505ee368f";
      };
    };
    "strip-json-comments-3.0.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-3.0.1.tgz";
        sha512 = "VTyMAUfdm047mwKl+u79WIdrZxtFtn+nBxHeb844XBQ9uMNTuTHdx2hc5RiAJYqwTj3wc/xe5HLSdJSkJ+WfZw==";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-color-6.1.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-6.1.0.tgz";
        sha512 = "qe1jfm1Mg7Nq/NSh6XE24gPXROEVsWHxC1LIx//XNlD9iw7YZQGjZNjYN7xGaEG6iKdA8EtNFW6R0gjnVXp+wQ==";
      };
    };
    "symbol-0.3.1" = {
      name = "symbol";
      packageName = "symbol";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/symbol/-/symbol-0.3.1.tgz";
        sha1 = "b6f9a900d496a57f02408f22198c109dda063041";
      };
    };
    "teleport-javascript-1.0.0" = {
      name = "teleport-javascript";
      packageName = "teleport-javascript";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/teleport-javascript/-/teleport-javascript-1.0.0.tgz";
        sha512 = "j1llvWVFyEn/6XIFDfX5LAU43DXe0GCt3NfXDwJ8XpRRMkS+i50SAkonAONBy+vxwPFBd50MFU8a2uj8R/ccLg==";
      };
    };
    "tough-cookie-2.5.0" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.5.0.tgz";
        sha512 = "nlLsUzgm1kfLXSXfRZMc1KLAugd4hqJHDTvc2hDIwS3mZAfMEuMbc03SujMF+GEcpaX/qboeycw6iO8JwVv2+g==";
      };
    };
    "tough-cookie-3.0.1" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-3.0.1.tgz";
        sha512 = "yQyJ0u4pZsv9D4clxO69OEjLWYw+jbgspjTue4lTQZLfV0c5l1VmK2y1JK8E9ahdpltPOaAThPcp5nKPUgSnsg==";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "uglify-js-3.7.5" = {
      name = "uglify-js";
      packageName = "uglify-js";
      version = "3.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-js/-/uglify-js-3.7.5.tgz";
        sha512 = "GFZ3EXRptKGvb/C1Sq6nO1iI7AGcjyqmIyOw0DrD0675e+NNbGO72xmMM2iEBdFbxaTLo70NbjM/Wy54uZIlsg==";
      };
    };
    "underscore-1.7.0" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz";
        sha1 = "6bbaf0877500d36be34ecaa584e0db9fef035209";
      };
    };
    "uri-js-4.2.2" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.2.2.tgz";
        sha512 = "KY9Frmirql91X2Qgjry0Wd4Y+YTdrdZheS8TFwvkbLWf/G5KNJDCh6pKL5OZctEW4+0Baa5idK2ZQuELRwPznQ==";
      };
    };
    "utcstring-0.1.0" = {
      name = "utcstring";
      packageName = "utcstring";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utcstring/-/utcstring-0.1.0.tgz";
        sha1 = "430fd510ab7fc95b5d5910c902d79880c208436b";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "uuid-3.3.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.3.2.tgz";
        sha512 = "yXJmeNaw3DnnKAOKJE51sL/ZaYfWJRl1pK9dr19YFCu0ObS231AB1/LbqTKRAQ5kw8A90rA6fr4riOUpTZvQZA==";
      };
    };
    "uuid-3.3.3" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.3.3.tgz";
        sha512 = "pW0No1RGHgzlpHJO1nsVrHKpOEIxkGg1xB+v0ZmdNH5OAeAwzAVrCnI2/6Mtx+Uys6iaylxa+D3g4j63IKKjSQ==";
      };
    };
    "uvm-1.7.8" = {
      name = "uvm";
      packageName = "uvm";
      version = "1.7.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/uvm/-/uvm-1.7.8.tgz";
        sha512 = "Uasp7fsWQBo+pZbtlA0C464vYC6uHDdSVbX08vIinvi7r/k1R9sSs7n2/rf8lHkYRR6l4I46i7/xsWdqvLKDVQ==";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "word-wrap-1.2.3" = {
      name = "word-wrap";
      packageName = "word-wrap";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/word-wrap/-/word-wrap-1.2.3.tgz";
        sha512 = "Hz/mrNwitNRh/HUAtM/VT/5VH+ygD6DV7mYKZAtHOrbs8U7lvPS6xf7EJKMF0uW1KJCl0H701g3ZGus+muE5vQ==";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "xmlbuilder-13.0.2" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "13.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-13.0.2.tgz";
        sha512 = "Eux0i2QdDYKbdbA6AM6xE4m6ZTZr4G4xF9kahI2ukSEMCzwce2eX9WlTI5J3s+NU7hpasFsr8hWIONae7LluAQ==";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
  };
in
{
  "newman-git://github.com/postmanlabs/newman#v4.5.7" = nodeEnv.buildNodePackage {
    name = "newman";
    packageName = "newman";
    version = "4.5.7";
    src = fetchgit {
      url = "git://github.com/postmanlabs/newman";
      rev = "aad61eb140d198e52c14949ffbabad8168aa86a8";
      sha256 = "348ebe75e609d359196971b9048c0d4ba24c93d01233f8dc1dd2ffd2b4298666";
    };
    dependencies = [
      sources."@postman/csv-parse-4.0.2"
      sources."@postman/tunnel-agent-0.6.3"
      sources."ajv-6.10.2"
      sources."ansi-regex-3.0.0"
      sources."ansi-styles-3.2.1"
      sources."array-uniq-1.0.3"
      sources."asn1-0.2.4"
      sources."assert-plus-1.0.0"
      sources."async-3.1.0"
      sources."asynckit-0.4.0"
      sources."aws-sign2-0.7.0"
      sources."aws4-1.9.0"
      sources."bcrypt-pbkdf-1.0.2"
      sources."bluebird-2.11.0"
      sources."caseless-0.12.0"
      sources."chalk-2.4.2"
      sources."chardet-0.8.0"
      sources."charset-1.0.1"
      sources."cli-progress-3.4.0"
      sources."cli-table3-0.5.1"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."colors-1.4.0"
      sources."combined-stream-1.0.8"
      sources."commander-4.0.1"
      sources."core-util-is-1.0.2"
      sources."crypto-js-3.1.9-1"
      sources."dashdash-1.14.1"
      sources."dbug-0.4.2"
      sources."delayed-stream-1.0.0"
      (sources."dom-serializer-0.2.2" // {
        dependencies = [
          sources."domelementtype-2.0.1"
          sources."entities-2.0.0"
        ];
      })
      sources."domelementtype-1.3.1"
      sources."domhandler-2.4.2"
      sources."domutils-1.7.0"
      sources."ecc-jsbn-0.1.2"
      sources."entities-1.1.2"
      sources."escape-html-1.0.3"
      sources."escape-string-regexp-1.0.5"
      sources."eventemitter3-4.0.0"
      sources."extend-3.0.2"
      sources."extsprintf-1.3.0"
      sources."faker-4.1.0"
      sources."fast-deep-equal-2.0.1"
      sources."fast-json-stable-stringify-2.1.0"
      sources."file-type-3.9.0"
      sources."filesize-6.0.1"
      sources."flatted-2.0.1"
      sources."forever-agent-0.6.1"
      sources."form-data-2.3.3"
      sources."getpass-0.1.7"
      sources."handlebars-4.5.3"
      sources."har-schema-2.0.0"
      sources."har-validator-5.1.3"
      (sources."has-ansi-2.0.0" // {
        dependencies = [
          sources."ansi-regex-2.1.1"
        ];
      })
      sources."has-flag-3.0.0"
      sources."htmlparser2-3.10.1"
      sources."http-reasons-0.1.0"
      sources."http-signature-1.2.0"
      sources."httpntlm-1.7.6"
      sources."httpreq-0.4.24"
      sources."iconv-lite-0.5.0"
      sources."inherits-2.0.4"
      (sources."intel-1.2.0" // {
        dependencies = [
          sources."ansi-regex-2.1.1"
          sources."ansi-styles-2.2.1"
          sources."chalk-1.1.3"
          sources."strip-ansi-3.0.1"
          sources."supports-color-2.0.0"
        ];
      })
      sources."ip-regex-2.1.0"
      sources."is-fullwidth-code-point-2.0.0"
      sources."is-typedarray-1.0.0"
      sources."isstream-0.1.2"
      sources."jsbn-0.1.1"
      sources."json-schema-0.2.3"
      sources."json-schema-traverse-0.4.1"
      sources."json-stringify-safe-5.0.1"
      sources."jsprim-1.4.1"
      sources."liquid-json-0.3.1"
      sources."lodash-4.17.15"
      sources."lodash.clonedeep-4.5.0"
      sources."lodash.escaperegexp-4.1.2"
      sources."lodash.isplainobject-4.0.6"
      sources."lodash.isstring-4.0.1"
      sources."lodash.mergewith-4.6.2"
      sources."marked-0.7.0"
      sources."mime-db-1.42.0"
      sources."mime-format-2.0.0"
      sources."mime-types-2.1.25"
      sources."minimist-0.0.8"
      sources."mkdirp-0.5.1"
      sources."neo-async-2.6.1"
      sources."node-oauth1-1.2.2"
      sources."number-is-nan-1.0.1"
      sources."oauth-sign-0.9.0"
      sources."object-assign-4.1.1"
      sources."object-hash-1.3.1"
      sources."optimist-0.6.1"
      sources."parse-ms-2.1.0"
      sources."performance-now-2.1.0"
      (sources."postcss-7.0.26" // {
        dependencies = [
          sources."supports-color-6.1.0"
        ];
      })
      sources."postman-collection-3.5.5"
      (sources."postman-collection-transformer-3.2.0" // {
        dependencies = [
          sources."commander-3.0.1"
        ];
      })
      (sources."postman-request-2.88.1-postman.16" // {
        dependencies = [
          sources."postman-url-encoder-1.0.1"
        ];
      })
      (sources."postman-runtime-7.21.0" // {
        dependencies = [
          sources."async-2.6.2"
          sources."tough-cookie-3.0.1"
        ];
      })
      (sources."postman-sandbox-3.5.2" // {
        dependencies = [
          sources."tough-cookie-3.0.1"
        ];
      })
      sources."postman-url-encoder-1.0.3"
      sources."pretty-ms-5.1.0"
      sources."psl-1.7.0"
      sources."punycode-2.1.1"
      sources."qs-6.5.2"
      sources."readable-stream-3.4.0"
      sources."resolve-from-5.0.0"
      sources."safe-buffer-5.2.0"
      sources."safer-buffer-2.1.2"
      sources."sanitize-html-1.20.1"
      sources."semver-6.3.0"
      (sources."serialised-error-1.1.3" // {
        dependencies = [
          sources."stack-trace-0.0.9"
        ];
      })
      sources."source-map-0.6.1"
      sources."srcset-1.0.0"
      sources."sshpk-1.16.1"
      sources."stack-trace-0.0.10"
      sources."stream-length-1.0.2"
      sources."strftime-0.10.0"
      sources."string-width-2.1.1"
      sources."string_decoder-1.3.0"
      sources."strip-ansi-4.0.0"
      sources."strip-json-comments-3.0.1"
      sources."supports-color-5.5.0"
      sources."symbol-0.3.1"
      sources."teleport-javascript-1.0.0"
      sources."tough-cookie-2.5.0"
      sources."tweetnacl-0.14.5"
      (sources."uglify-js-3.7.5" // {
        dependencies = [
          sources."commander-2.20.3"
        ];
      })
      sources."underscore-1.7.0"
      sources."uri-js-4.2.2"
      sources."utcstring-0.1.0"
      sources."util-deprecate-1.0.2"
      sources."uuid-3.3.3"
      (sources."uvm-1.7.8" // {
        dependencies = [
          sources."uuid-3.3.2"
        ];
      })
      sources."verror-1.10.0"
      sources."word-wrap-1.2.3"
      sources."wordwrap-0.0.3"
      sources."xmlbuilder-13.0.2"
      sources."xtend-4.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Command-line companion utility for Postman";
      homepage = https://github.com/postmanlabs/newman;
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}