# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  networking.hostName = "zen";

  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "nvme" "ahci" "usbhid" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d1402701-db0a-4a98-9ce6-7195c82993fe";
      fsType = "f2fs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1085-E9AE";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/7fdbfad8-8942-42a9-9143-1b93c2ee4590";
      fsType = "f2fs";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/e83a335f-a231-4051-885b-c6b0cea4c2e6";
      fsType = "f2fs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3ff15ccb-2549-4f34-bf8f-7adbd4246254"; }
    ];

}
